name: Node.js Package
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      # Setup .npmrc file to publish to npm
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: yarn

      - name: Compile TypeScript
        run: yarn tsc

      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
